### ISSUE TITLE
Path in bower.json not valid - case-sensitivity

### ISSUE THREAD

**Issue by deel77** [kentcdodds/api-check#11]
I have problem in my project using bower generated index.html because in bower.json in apiCheck there is 

```
"main": "dist/apicheck.js",
```

but the actual file in `dist` directory is `apiCheck.js`

please correct the case (it would be best to change the name of file in dist, not in bower.json, better to keep it lowercase)

**Comment by prismsoundzero** [comment]
I've just spent few hours trying to understand why apiCheck.js was not included by wiredep in my index.html on our CI server (SuSE Linux) while it was on my computer (Mac OS) and I've just found out that it was because of the case in bower.json main. I was about to open a ticket but I can see that @deel77 had the same issue.

**Comment by kentcdodds** [comment]
Super sorry about that! I'll have a fix in just a second!

**Comment by kentcdodds** [comment]
Fixed in 6.0.11. Let me know if you have any other issues!

**Comment by kentcdodds** [comment]
@prismsoundzero, I'm super sorry that you lost hours on this issue. Total oversight on my part. If you're ever in Utah, let me know and I'll take you out for dinner or something.

@deel77, I didn't change the filename because that would have been a breaking change for people who are using script tags and I don't see a reason to have it all lower case. I hope this isn't a problem for you.

**Comment by deel77** [comment]
@kentcdodds thanks for quick response, it works perfectly :+1:

**Comment by kentcdodds** [comment]
@deel77 about to do a breaking change release. I'm thinking that I'll rename the file to `api-check.js` so it's consistent with the package name. Do you see any problem with that?

**Comment by deel77** [comment]
@kentcdodds I think it is a good practice to keep filenames in lowercase especially in such multiplatform projects as is anything connected with javascript. Therefore, I support your decision.

**Comment by prismsoundzero** [comment]
@kentcdodds Thanks for fixing this so quickly. I don't plan to go to the US in the near future but hey we never now so thanks anyway. As @deel77 said, I'm also more confortable with lowercase filenames and api-check.js seems to be the best variant.
